"""add tb_product_indications

Revision ID: 85f4c0d9e694
Revises: 905a06eb0ee4
Create Date: 2026-07-29 09:35:49.278558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f4c0d9e694'
down_revision: Union[str, Sequence[str], None] = '905a06eb0ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_product_indications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_score_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend_status', sa.Enum('SEM_HISTORICO_SUFICIENTE', 'CRESCIMENTO_FORTE', 'CRESCIMENTO_MODERADO', 'ESTAVEL', 'QUEDA_MODERADA', 'QUEDA_FORTE', name='trend_status_enum', native_enum=False, length=30), nullable=False),
    sa.Column('indicated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tb_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_score_id'], ['tb_product_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_product_indications_category_id'), 'tb_product_indications', ['category_id'], unique=False)
    op.create_index(op.f('ix_tb_product_indications_indicated_at'), 'tb_product_indications', ['indicated_at'], unique=False)
    op.create_index(op.f('ix_tb_product_indications_product_id'), 'tb_product_indications', ['product_id'], unique=False)
    op.create_index(op.f('ix_tb_product_indications_product_score_id'), 'tb_product_indications', ['product_score_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_product_indications_product_score_id'), table_name='tb_product_indications')
    op.drop_index(op.f('ix_tb_product_indications_product_id'), table_name='tb_product_indications')
    op.drop_index(op.f('ix_tb_product_indications_indicated_at'), table_name='tb_product_indications')
    op.drop_index(op.f('ix_tb_product_indications_category_id'), table_name='tb_product_indications')
    op.drop_table('tb_product_indications')
    # ### end Alembic commands ###
