"""add tb_customers

Revision ID: 883e7a5e07a5
Revises: a3f2d8c1b905
Create Date: 2026-07-29 13:19:55.627294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883e7a5e07a5'
down_revision: Union[str, Sequence[str], None] = 'a3f2d8c1b905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grafana_username', sa.String(length=100), nullable=False),
    sa.Column('shopee_app_id', sa.String(length=255), nullable=True),
    sa.Column('shopee_app_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grafana_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_customers')
    # ### end Alembic commands ###
