"""initial schema

Revision ID: 905a06eb0ee4
Revises: 
Create Date: 2026-07-26 16:35:02.842118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905a06eb0ee4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_age_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('minimum_age_months', sa.Integer(), nullable=True),
    sa.Column('maximum_age_months', sa.Integer(), nullable=True),
    sa.Column('is_pregnancy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_age_ranges_code'), 'tb_age_ranges', ['code'], unique=True)
    op.create_table('tb_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tb_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_categories_parent_id'), 'tb_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tb_categories_slug'), 'tb_categories', ['slug'], unique=True)
    op.create_table('tb_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source_type', sa.Enum('OFFICIAL_API', 'PUBLIC_FEED', 'PUBLIC_PAGE', 'SIMPLE_HTTP', 'MOCK', name='source_type_enum', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_authentication', sa.Boolean(), nullable=False),
    sa.Column('collection_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sources_code'), 'tb_sources', ['code'], unique=True)
    op.create_table('tb_collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='collection_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_ignored', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tb_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_collection_runs_execution_id'), 'tb_collection_runs', ['execution_id'], unique=True)
    op.create_index(op.f('ix_tb_collection_runs_source_id'), 'tb_collection_runs', ['source_id'], unique=False)
    op.create_table('tb_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('age_range_id', sa.Integer(), nullable=True),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', name='moderation_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['age_range_id'], ['tb_age_ranges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['tb_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_products_age_range_id'), 'tb_products', ['age_range_id'], unique=False)
    op.create_index(op.f('ix_tb_products_canonical_hash'), 'tb_products', ['canonical_hash'], unique=True)
    op.create_index(op.f('ix_tb_products_category_id'), 'tb_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_tb_products_normalized_name'), 'tb_products', ['normalized_name'], unique=False)
    op.create_table('tb_collection_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['tb_collection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_collection_errors_collection_run_id'), 'tb_collection_errors', ['collection_run_id'], unique=False)
    op.create_table('tb_product_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('social_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend_status', sa.Enum('SEM_HISTORICO_SUFICIENTE', 'CRESCIMENTO_FORTE', 'CRESCIMENTO_MODERADO', 'ESTAVEL', 'QUEDA_MODERADA', 'QUEDA_FORTE', name='trend_status_enum', native_enum=False, length=30), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('calculation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_product_scores_calculated_at'), 'tb_product_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_tb_product_scores_product_id'), 'tb_product_scores', ['product_id'], unique=False)
    op.create_table('tb_product_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('affiliate_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'UNKNOWN', name='availability_enum', native_enum=False, length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['tb_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_product_sources_source_external')
    )
    op.create_index('ix_product_sources_source_url_hash', 'tb_product_sources', ['source_id', 'url_hash'], unique=True, postgresql_where='external_id IS NULL')
    op.create_index(op.f('ix_tb_product_sources_product_id'), 'tb_product_sources', ['product_id'], unique=False)
    op.create_index(op.f('ix_tb_product_sources_source_id'), 'tb_product_sources', ['source_id'], unique=False)
    op.create_table('tb_publication_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', name='publication_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_publication_status_product_id'), 'tb_publication_status', ['product_id'], unique=True)
    op.create_table('tb_product_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_source_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'UNKNOWN', name='availability_enum', native_enum=False, length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_source_id'], ['tb_product_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_product_history_collected_at'), 'tb_product_history', ['collected_at'], unique=False)
    op.create_index(op.f('ix_tb_product_history_product_source_id'), 'tb_product_history', ['product_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_product_history_product_source_id'), table_name='tb_product_history')
    op.drop_index(op.f('ix_tb_product_history_collected_at'), table_name='tb_product_history')
    op.drop_table('tb_product_history')
    op.drop_index(op.f('ix_tb_publication_status_product_id'), table_name='tb_publication_status')
    op.drop_table('tb_publication_status')
    op.drop_index(op.f('ix_tb_product_sources_source_id'), table_name='tb_product_sources')
    op.drop_index(op.f('ix_tb_product_sources_product_id'), table_name='tb_product_sources')
    op.drop_index('ix_product_sources_source_url_hash', table_name='tb_product_sources', postgresql_where='external_id IS NULL')
    op.drop_table('tb_product_sources')
    op.drop_index(op.f('ix_tb_product_scores_product_id'), table_name='tb_product_scores')
    op.drop_index(op.f('ix_tb_product_scores_calculated_at'), table_name='tb_product_scores')
    op.drop_table('tb_product_scores')
    op.drop_index(op.f('ix_tb_collection_errors_collection_run_id'), table_name='tb_collection_errors')
    op.drop_table('tb_collection_errors')
    op.drop_index(op.f('ix_tb_products_normalized_name'), table_name='tb_products')
    op.drop_index(op.f('ix_tb_products_category_id'), table_name='tb_products')
    op.drop_index(op.f('ix_tb_products_canonical_hash'), table_name='tb_products')
    op.drop_index(op.f('ix_tb_products_age_range_id'), table_name='tb_products')
    op.drop_table('tb_products')
    op.drop_index(op.f('ix_tb_collection_runs_source_id'), table_name='tb_collection_runs')
    op.drop_index(op.f('ix_tb_collection_runs_execution_id'), table_name='tb_collection_runs')
    op.drop_table('tb_collection_runs')
    op.drop_index(op.f('ix_tb_sources_code'), table_name='tb_sources')
    op.drop_table('tb_sources')
    op.drop_index(op.f('ix_tb_categories_slug'), table_name='tb_categories')
    op.drop_index(op.f('ix_tb_categories_parent_id'), table_name='tb_categories')
    op.drop_table('tb_categories')
    op.drop_index(op.f('ix_tb_age_ranges_code'), table_name='tb_age_ranges')
    op.drop_table('tb_age_ranges')
    # ### end Alembic commands ###
